<template>
  <div class="loadingio-spinner-rolling-9f4hja5xffr">
    <div class="ldio-gpklibk3god">
      <div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-gpklibk3god {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-gpklibk3god div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #ffffff;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-gpklibk3god div {
  animation: ldio-gpklibk3god 2.5027027027027026s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-9f4hja5xffr {
  width: 21px;
  height: 21px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-gpklibk3god {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.21);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gpklibk3god div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
